src/charm.py
tests/integration/test_charm.py
tests/unit/test_operator.py

Do not proceed with main function unless it is a leader unit
It was causing transient errors when switching units (e.g. upgrade charm, public url config update)
Tested this against the integration test in [this pr](https://github.com/canonical/dex-auth-operator/pull/40). I was able to wait for idle with `raise_on_error=True` after updating public url

exit function if not a leader

---

test-requirements.txt

old black versions would fail as certain file no longer exist in click. Update test dependency to use black's latest version

use latest black

---

.github/workflows/integrate.yaml
.github/workflows/on_pull_request.yaml
.github/workflows/on_push.yaml
.github/workflows/publish.yaml
.github/workflows/release.yaml

Charming actions updated according to the ones agreed on template-operator charm.
The aim was to:
- add release charm action
- have two publish actions for `on: push` and `on: pull_request`:
- on pull_request, publish to branch no matter if tests passed (tests and publish should run simultaneously)
- on push, publish to latest/edge only if tests passed
- avoid re-running the tests on pull_request
- use reusable workflows in order to avoid duplication of code.
Note: this is a single-charm repo with one resource.

Add charming actions

---

test-requirements.txt

Unpins flake8 to fix a version incompatibility between flake8 and pyflake8.  Previously, we pinned flake8 because some of the flake8 packages we used did not support the latest version.  Now, those are fixed, but pyflake8 does not support the older version of flake8.  Unpinning fixes all of this.

fix: unpin flake8

---

src/charm.py
tests/unit/test_operator.py

fixes #64 
In the upgrade of oidc from `fef11c3` -> `e236439`, an env variable `OIDC_STATE_STORE_PATH` was introduced that defaults to "/var/lib/authservice/oidc_state.db", reference [here](https://github.com/arrikto/oidc-authservice/tree/master#options). Currently, the /var/lib/authservice/ path does not exist in the container causing the error `fatal msg="Error creating oidc state store: open /var/lib/authservice/data.db: no such file or directory"`.

fix: define OIDC_STATE_STORE_PATH env variable

---

tools/get-images.sh

Used by CVE scanning workflows and can be used to collect images URL for airgapped setup. Script is specific for track/ckf-1.7 branch to capture all images for that branch. Branch is handled in kubeflow-ci and bundle automation using bundle file.
Summary of changes:
- Re-designed get images script to retrieve all images for current branch. Branch management is done outside of this script.

feat: updated get images script without branch checkout for track/ckf-1.7

---

src/charm.py
tests/integration/test_charm.py
tests/unit/test_operator.py

We realised in https://github.com/canonical/oidc-gatekeeper-operator/issues/107 that charm doesn't block public-url is not configured. Thus, this fixes the issue setting the status to Blocked when configuration `public-url` is not there.
Closes https://github.com/canonical/oidc-gatekeeper-operator/issues/107

fix: Block charm when public-url is not configured

---

config.yaml
src/charm.py

fixes #99 
Adds a config to the charm that enables setting the USERID_CLAIM env var. This env var tells oidc what claim to use in setting the value of the `kubeflow-userid` header.
* deploy Charmed Kubeflow latest/edge
* Access the dashboard - [instructions](https://charmed-kubeflow.io/docs/get-started-with-charmed-kubeflow#heading--configure-the-charmed-kubeflow-components)
* refresh oidc to the charm in this branch
* make a request to jupyter-ui by accessing Notebooks from the dashboard
**Note** we can use the jupyter-ui logs to check on this value since it's printed in the logs every time jupyter-ui gets a request, see [upstream code](https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/authn.py#L19-L20).
* set the …

feat: add config for USERID_CLAIM env var

---

metadata.yaml

Changes the source of the oci-image from arrikto registry to kubeflow-owned registry.
This commit should also be cherry-picked to main.

feat: set oidc-authservice image source to kubeflow-owned registry

---

src/charm.py
tests/unit/test_operator.py

Fix https://github.com/canonical/oidc-gatekeeper-operator/issues/112
Added test which simulates the problematic situation where on pebble ready is triggered as last hook and there are no other hooks. We expect in this situation to handle this event.

Fix waiting for pod startup

---

src/charm.py
tests/unit/test_operator.py

Back port for this fix https://github.com/canonical/oidc-gatekeeper-operator/pull/118

Pod startup fix backport

---

src/charm.py

This adds a working-dir argument for the oidc-authservice pebble plan.  This is required to allow a rock of the upstream image to be drop-in replacement.  
This also may fix #126, although I don't understand why this would be the cause of that issue.

explicitly set working-dir for workload in charm.py

---

metadata.yaml

Closes #131
Testing notes: Because this repo's test suite has given some false passes lately, I've also tested this manually using dex-auth's tests and it worked as expected.  Once this is merged and pushed to charmhub, we should re-trigger dex-auth's CI just to demonstrate publicly how it really works

use rock for oidc-authservice on `main` for ckf-1.8

---

metadata.yaml
src/charm.py

Cherry pick from main to track/ckf-1.8:
* explicitly set workingdir for workload in charm.py 
* [use rock for oidc-authservice on main for ckf-1.8

cherry pick rock, `workingdir` fix to main

---

src/charm.py

These variables are required by the OIDC Authservice to correctly redirect users along the authentication flow.
* OIDC_AUTH_URL: is used as the URL tht Authservice will hit for initiating the auth flow
* AFTER_LOGIN_URL: is used for redirecting after login.
* AFTER_LOGOUT_URL: is used for redirecting after logout. 
These variables are required because the default behaviour of OIDC Authservice is to redirect to URLs that can be undesired, by setting them up, we have a deterministic way of setting where users should be redirected.
Part of canonical/bundle-kubeflow#608

feat: add OIDC_AUTH_URL and AFTER_LOGIN_URL env variables

---

src/charm.py

* feat: add OIDC_AUTH_URL and AFTER_LOGIN_URL env variables
These variables are required by the OIDC Authservice to correctly redirect users along the authentication flow.
* OIDC_AUTH_URL: is used as the URL tht Authservice will hit for initiating the auth flow
* AFTER_LOGIN_URL: is used for redirecting after login
* AFTER_LOGOUT_URL: is used for redirecting after logout.
These variables are required because the default behaviour of OIDC Authservice is to redirect to URLs that can be undesired, by setting them up, we have a deterministic way of setting where users should be redirected.
Part of canonical/bundle-kubeflow#608
Fixes #138

feat: add OIDC_AUTH_URL and AFTER_LOGIN_URL env variables (#136)

---

tests/integration/test_charm.py

The integration tests were deploying versions of dependency charms that do not correspond to the current release of this charm(s). This commit brings all the correct versions and configure charms accordingly to ensure the integration tests execute in the same environment as this version of the charm(s) was design for.

tests: point all the integration charm deps to their 1.8 versions

---

.github/workflows/integrate.yaml
requirements-integration.txt
requirements-unit.in
requirements-unit.txt
requirements.txt

Bumping juju and ops packages to use them in newer versions of the charms, plus testing them in a CI with a more recent juju version.
Part of canonical/bundle-kubeflow#859
Merge after https://github.com/canonical/oidc-gatekeeper-operator/pull/143

build: bump juju, ops versions in ci and requirements files

---

tests/integration/test_charm.py

Pins dependencies in the integration tests to their corresponding channels for this release.
Ref: https://github.com/canonical/bundle-kubeflow/issues/866

pin integration test dependencies, refactor constants in tests for track/ckf-1.8

---

tests/integration/test_charm.py

Pins dependencies in the integration tests to their corresponding channels for this development branch.
Ref: https://github.com/canonical/bundle-kubeflow/issues/866

pin integration test dependencies, refactor constants in tests for main

---

.github/workflows/integrate.yaml

Part of canonical/bundle-kubeflow#944

ci: use juju 3.4/stable instead of 3.5/stable in track ckf-1.8

---

lib/charms/loki_k8s/v1/loki_push_api.py
metadata.yaml
requirements-integration.in
requirements-integration.txt
requirements-unit.txt
requirements.in
requirements.txt
src/charm.py
tests/integration/test_charm.py
tests/unit/test_operator.py

Use LogForwarder from loki_push_api library to forwards all logs from workload container to Loki. This requires to use ops 2.9 or newer, so it was needed to be updated.
fixes: #152
How I tested it:
```bash
$ tox -e integration -- --keep-models --model kubeflow
$ juju switch kubeflow
$ charmcraft pack
Created 'oidc-gatekeeper_ubuntu-20.04-amd64.charm'.
Charms packed:
oidc-gatekeeper_ubuntu-20.04-amd64.charm
$ juju refresh oidc-gatekeeper --path ./oidc-gatekeeper_ubuntu-20.04-amd64.charm 
Added local charm "oidc-gatekeeper", revision 1, to the model
adding endpoint "logging" to default space "alpha"
no change to endpoints in space "alpha": client-secret, ingress, ingress-auth, oidc-client
$ juju consume u1-k8s:cos.loki-logging
$ juju integrate grafana-agent-k8s loki-logging
$ juju integrate …
```

Add logging relation to oidc-gatekeeper

---

README.md

Add a section describing how this charm can only be used as an OIDC client when Dex and Charmed Kubeflow are deployed in the model; otherwise it will fail, as there are multiple parts of this charm's code that are tightly coupled to those.
Fixes #159

docs: add Limitations section on README

---

README.md
charmcraft.yaml
config.yaml
lib/charms/dex_auth/v0/dex_oidc_config.py
metadata.yaml
requirements-unit.txt
requirements.in
requirements.txt
src/charm.py
tests/integration/test_charm.py
tests/unit/test_operator.py

This commit integrates the `oidc-gatekeeper` charm with `dex-auth` via the `dex-oidc-config` interface.
`dex-auth` (see https://github.com/canonical/dex-auth-operator/issues/203) recently introduced the aforementioned interface, which will help us remove the `public-url` configuration option as the main way of configuring oidc-gatekeeper's OIDC_AUTH_PROVIDER env variable. The new relation provides all the information that is required for setting that env variable, so this charm and its users should not change it.
The changes in this PR include:
* Removing the `public-url` configuration option entirely (a backwards compatible solution is not required in this case because dex-auth already has it) -> this tackles #157
* Removing all traces of the public-url from the charm code and test code …

feat: integrate with dex-oidc-config interface and remove `public-url`

---

README.md
charmcraft.yaml
config.yaml
lib/charms/dex_auth/v0/dex_oidc_config.py
metadata.yaml
requirements-unit.txt
requirements.in
requirements.txt
src/charm.py
tests/integration/test_charm.py
tests/unit/test_operator.py

This PR introduces the following changes in `main`:
* docs: add Limitations section on README (#166)
* feat: integrate with dex-oidc-config interface and remove public-url (#163)

feat, docs: merge KF-5546-oidc-provider-dev-branch into main

---

.github/workflows/publish.yaml

Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993

ci(upload-charm): use charmcraft from latest/candidate in track/ckf-1.8

---

requirements-fmt.txt
requirements-integration.txt
requirements-lint.txt
requirements-unit.in
requirements-unit.txt
requirements.txt
tox.ini

* Pin pip to 24.2 due to https://github.com/jazzband/pip-tools/issues/2131
* Update python dependencies using 'tox -e update-requirements'
* Remove unused pytest-lazy-fixture package
Ref canonical/bundle-kubeflow#1177
Ref canonical/bundle-kubeflow#1185

chore: update python dependencies + pin pip

---

metadata.yaml

Integrates the latest released version of the container image in preparation for a new release.

chore: integrate ckf-1.10-5c30ade image into charm
